# docker-compose.yml for local
version: '3.7'

services:

  web: 
    build:
      context: ./web
      dockerfile: Dockerfile
    image: kvs2_web_local
    container_name: kvs2_web
    restart: always
    depends_on:
      - app
    ports:
      - 80:80
    environment:
      PORT         : 80
      API_PROXY_URL: "http://app:80"

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: kvs2_app_local
    container_name: kvs2_app
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PORT:       80
      REDIS_HOST: db
      REDIS_PORT: 6379
      REDIS_DB:   0

  db:
    image: redis:5.0.6-alpine3.10
    restart: always
    container_name: kvs2_db
    volumes:
      - redis_volume:/data

volumes:
  redis_volume:
    driver: local