version: '3.7'
services:
  webtest:
    build:
      context: ./webtest
      dockerfile: Dockerfile
    image: c8kvs_build_webtest  
  web: 
    build:
      context: ./web
      dockerfile: Dockerfile
    image: c8kvs_build_web
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: c8kvs_build_app