apiVersion: v1
kind: Pod
metadata:
  name: kvs2-db
  labels: 
    svc2pod: kvs2-db
spec:
  containers:
    - name: redis
      image: redis:5.0.6-alpine3.10
      ports:
      - name: redis
        containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: kvs2-db
spec:
  selector:
    svc2pod: kvs2-db
  ports:
    - port: 6379
      targetPort: redis
  type: ClusterIP